
FROM maven:3.8.6-openjdk-18 AS build
COPY tredara-backend /usr/src/app/
RUN mvn -f /usr/src/app/pom.xml clean package -DskipTests=true

FROM openjdk:18-alpine
COPY --from=build /usr/src/app//target/tredara-backend-0.0.1.jar /usr/src/app/tredara-backend-0.0.1.jar
#EXPOSE 8080
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=prod", "/usr/src/app/tredara-backend-0.0.1.jar"]