services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'natflix'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: natflix-database-server
    ports:
      - '3306:3306'
    networks:
      - natflix-nw
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    depends_on:
      - db
    image: natflix-backend-server:1.1
    container_name: natflix-backend-server
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - natflix-nw
    build:
      context: .
      dockerfile: Dockerfile.backend

  frontend:
    depends_on:
      - backend
    image: natflix-frontend-server:1.1
    container_name: frontend-server
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - natflix-nw
    build:
      context: .
      dockerfile: Dockerfile.frontend
networks:
    natflix-nw:
       driver: bridge