# Create image based on the official Node 17 image from dockerhub
FROM node:latest

# Get all the code needed to run the app
COPY tredara-frontend /usr/src/app/

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Install dependecies
RUN npm cache clean --force
RUN npm install 

# Expose the port the app runs in
#EXPOSE 3000

# Serve the app
ENTRYPOINT [ "npm", "run", "start"]
